/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package z.codearchive;
import gui.AnalyzeFreeTextDialog;

import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import javax.swing.GroupLayout.Alignment;

import logic.SamOpenCalaisEntityExtractionViewModel;

/**
 *
 * @author Sammy
 */
public class MainFrame extends javax.swing.JFrame {


	private static final long serialVersionUID = 1L;
	
	SammEngine SE;
	SamOpenCalaisEntityExtractionViewModel sasClassification;

    public MainFrame() {
        initComponents();
        
         SE = new SammEngine();
         sasClassification = new SamOpenCalaisEntityExtractionViewModel();
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 326, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
        
        JMenuBar menuBar = new JMenuBar();
        setJMenuBar(menuBar);
        
        JMenu mnNewMenu = new JMenu("NLP");
        menuBar.add(mnNewMenu);
        
        JRadioButton rdbtnNewRadioButton = new JRadioButton("OpenCalais Service");
        mnNewMenu.add(rdbtnNewRadioButton);
        
        JRadioButton rdbtnNewRadioButton_1 = new JRadioButton("SAS Text Analysis Server");
        mnNewMenu.add(rdbtnNewRadioButton_1);
        
        JMenu mnNewMenu_1 = new JMenu("Configure");
        menuBar.add(mnNewMenu_1);
        
        JButton btnNewButton = new JButton("Configure OpenCalais Connection");
        mnNewMenu_1.add(btnNewButton);
        
        JButton btnNewButton_1 = new JButton("Configure SAS Text Analytics Connection");
        mnNewMenu_1.add(btnNewButton_1);
        
        JMenu mnNewMenu_2 = new JMenu("Quick");
        menuBar.add(mnNewMenu_2);
        
        JButton btnNewButton_2 = new JButton("Open Text Pane Dialog");
        btnNewButton_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.out.println("here is something");
        		AnalyzeFreeTextDialog cck = new AnalyzeFreeTextDialog();
        		cck.setVisible(true);
        	}
        });
        mnNewMenu_2.add(btnNewButton_2);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
}
