/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package z.codearchive;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JButton;

import java.awt.FlowLayout;

import javax.swing.JTextPane;

import logic.SamOpenCalaisEntityExtractionViewModel;
import models.SemanticAnalysisProjectConfigurationMetadata;

public class SemanticAnalyticOpenCalaisPanelComponent1 extends
		javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SamOpenCalaisEntityExtractionViewModel OCAO = null;
	private StringBuilder strbif = null;

	public SemanticAnalyticOpenCalaisPanelComponent1() {
		initComponents();

		OCAO = new SamOpenCalaisEntityExtractionViewModel();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();
		jResultsPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jLabel3 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();

		jResultsPanel4.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(0, 0, 0), 1, true));

		jScrollPane1.setViewportView(jTextPane1);

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Results / log - output");

		jButton3.setForeground(new java.awt.Color(255, 0, 51));
		jButton3.setText("save");

		jButton4.setForeground(new java.awt.Color(255, 0, 51));
		jButton4.setText("clear");

		javax.swing.GroupLayout jResultsPanel4Layout = new javax.swing.GroupLayout(
				jResultsPanel4);
		jResultsPanel4.setLayout(jResultsPanel4Layout);
		jResultsPanel4Layout
				.setHorizontalGroup(jResultsPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jResultsPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jResultsPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jResultsPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(48,
																				48,
																				48)
																		.addComponent(
																				jButton3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton4)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addComponent(
																jScrollPane1))
										.addContainerGap()));
		jResultsPanel4Layout
				.setVerticalGroup(jResultsPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jResultsPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jResultsPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jButton3)
														.addComponent(jButton4))
										.addGap(7, 7, 7)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												149, Short.MAX_VALUE)
										.addContainerGap()));

		jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 0, 0), 1, true));
		jPanel2.setLayout(null);
		GroupLayout groupLayout = new GroupLayout(this);
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
		);
		setLayout(groupLayout);
	}// </editor-fold>//GEN-END:initComponents
	private void buildListOfFilesAndDirectoriesRecurivlyForStringBuilder(File[] sourfilestuff) {
		for (File perfile : sourfilestuff) {
			if (perfile.isDirectory()) {
				strbif = strbif.append(perfile.getAbsolutePath());
				strbif = strbif.append("\n");
				buildListOfFilesAndDirectoriesRecurivlyForStringBuilder(perfile.listFiles());
			} else {
				strbif = strbif.append("-----");
				strbif = strbif.append(perfile.getAbsolutePath());
				strbif = strbif.append("\n");
			}
		}
	}
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jResultsPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane jTextPane1;
}
