/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ViewModels.SamOpenCalaisEntityExtractionViewModel;
import Models.SemanticAnalysisProjectConfigurationMetadata;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.FlowLayout;
import javax.swing.JTextPane;

public class SemanticAnalyticOpenCalaisPanelComponent1 extends
		javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SamOpenCalaisEntityExtractionViewModel OCAO = null;
	private StringBuilder strbif = null;

	public SemanticAnalyticOpenCalaisPanelComponent1() {
		initComponents();

		OCAO = new SamOpenCalaisEntityExtractionViewModel();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();
		jResultsPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jLabel3 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jExtractTextToTextFieldButton = new javax.swing.JButton();
		jExtractTextToTextFieldButton.setBounds(288, 173, 141, 23);
		jStartSelectTextFileDialogForTextButton = new javax.swing.JButton();
		jStartSelectTextFileDialogForTextButton.setBounds(10, 200, 141, 23);
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setBounds(246, 128, 183, 14);
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox1.setBounds(294, 229, 135, 23);
		jButton1 = new javax.swing.JButton();
		jButton1.setBounds(10, 259, 141, 23);
		jButton2 = new javax.swing.JButton();
		jButton2.setBounds(288, 202, 141, 23);
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator1.setBounds(221, 183, 23, 110);
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setBounds(10, 175, 62, 14);
		jLabel13 = new javax.swing.JLabel();
		jLabel13.setBounds(10, 234, 82, 14);
		jSelectFileToReadTextTextField = new javax.swing.JTextField();
		jSelectFileToReadTextTextField.setBounds(10, 142, 419, 20);
		jLabel14 = new javax.swing.JLabel();
		jLabel14.setBounds(349, 11, 80, 36);
		jLabel15 = new javax.swing.JLabel();
		jLabel15.setBounds(359, 46, 58, 15);

		jResultsPanel4.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(0, 0, 0), 1, true));

		jScrollPane1.setViewportView(jTextPane1);

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Results / log - output");

		jButton3.setForeground(new java.awt.Color(255, 0, 51));
		jButton3.setText("save");

		jButton4.setForeground(new java.awt.Color(255, 0, 51));
		jButton4.setText("clear");

		javax.swing.GroupLayout jResultsPanel4Layout = new javax.swing.GroupLayout(
				jResultsPanel4);
		jResultsPanel4.setLayout(jResultsPanel4Layout);
		jResultsPanel4Layout
				.setHorizontalGroup(jResultsPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jResultsPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jResultsPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jResultsPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(48,
																				48,
																				48)
																		.addComponent(
																				jButton3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton4)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addComponent(
																jScrollPane1))
										.addContainerGap()));
		jResultsPanel4Layout
				.setVerticalGroup(jResultsPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jResultsPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jResultsPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jButton3)
														.addComponent(jButton4))
										.addGap(7, 7, 7)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												149, Short.MAX_VALUE)
										.addContainerGap()));

		jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				0, 0, 0), 1, true));

		jExtractTextToTextFieldButton.setText("Preview Text");
		jExtractTextToTextFieldButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						readFileTextAndPrintToTextPanel(evt);
					}
				});

		jStartSelectTextFileDialogForTextButton
				.setText("Select File be analyzed");
		jStartSelectTextFileDialogForTextButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						selectTextFileDialogForTextButtonActionPerformed(evt);
					}
				});

		jLabel8.setText("Select File or Directory to be Analyzed");

		jCheckBox1.setForeground(new java.awt.Color(255, 0, 51));
		jCheckBox1.setSelected(true);
		jCheckBox1.setText("Include Sub-directories");

		jButton1.setText("Select  Directory");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectDirecotryTobeProcessed(evt);
			}
		});

		jButton2.setText("List File and Directory");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				printListingOfDirectoryButton2ActionPerformed(evt);
			}
		});

		jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

		jLabel9.setText("By Single File");

		jLabel13.setText("By Batch Process");

		jSelectFileToReadTextTextField.setName(""); // NOI18N

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		jLabel14.setText("SAM");

		jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel15.setText("Utility Tool");
		
		button = new JButton();
		button.setBounds(322, 259, 107, 23);
		button.setText("Analyze txt File");
		jPanel2.setLayout(null);
		jPanel2.add(button);
		jPanel2.add(jSelectFileToReadTextTextField);
		jPanel2.add(jStartSelectTextFileDialogForTextButton);
		jPanel2.add(jExtractTextToTextFieldButton);
		jPanel2.add(jLabel9);
		jPanel2.add(jSeparator1);
		jPanel2.add(jLabel13);
		jPanel2.add(jButton1);
		jPanel2.add(jButton2);
		jPanel2.add(jCheckBox1);
		jPanel2.add(jLabel8);
		jPanel2.add(jLabel14);
		jPanel2.add(jLabel15);
		GroupLayout groupLayout = new GroupLayout(this);
		groupLayout.setHorizontalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
		);
		groupLayout.setVerticalGroup(
			groupLayout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
		);
		
		JTextPane textPane = new JTextPane();
		textPane.setBounds(10, 11, 329, 110);
		jPanel2.add(textPane);
		setLayout(groupLayout);
	}// </editor-fold>//GEN-END:initComponents

	
	private void selectTextFileDialogForTextButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jStartSelectTextFileDialogForTextButtonActionPerformed
		// select single file for analysis
		jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
		int returnVal = jFileChooser1.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = jFileChooser1.getSelectedFile();
			try {

				OCAO.setFileMain(file);
				jSelectFileToReadTextTextField.setText(file.getAbsolutePath());

			} catch (Exception ex) {
				System.out.println("problem accessing file"	+ file.getAbsolutePath());
			}
		} else {
			System.out.println("File access cancelled by user.");
		}

	}// GEN-LAST:event_jStartSelectTextFileDialogForTextButtonActionPerformed
	private void selectDirecotryTobeProcessed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
			// select directory for batch processing of documents.
		
		jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		jFileChooser1.setDialogTitle("Select Directory, please!");
		jFileChooser1.setAcceptAllFileFilterUsed(false);

		if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			File directoryPath = jFileChooser1.getSelectedFile();
			OCAO.setDirectoryForBatchProcessing(directoryPath);
			jSelectFileToReadTextTextField.setText(jFileChooser1.getSelectedFile().getAbsolutePath());

		} else {
			System.out.println("No Selection ");
		}

	}// GEN-LAST:event_jButton1ActionPerformed
	private void readFileTextAndPrintToTextPanel(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jExtractTextToTextFieldButtonActionPerformed
		// preview text content in the textpanel
		try {
			if (OCAO.getFileMain() != null	& OCAO.getFileMain().isDirectory() == false) {
	//			jTextForOpenCalaisToAnalyzeTextPane.read(new FileReader(OCAO.getFileMain()), null);
			}
		} catch (Exception e) {
		}

	}// GEN-LAST:event_jExtractTextToTextFieldButtonActionPerformed

	private void printListingOfDirectoryButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

		strbif = new StringBuilder();
		System.out.println(OCAO.getDirectoryForBatchProcessing().listFiles().length);
		buildListOfFilesAndDirectoriesRecurivlyForStringBuilder(OCAO.getDirectoryForBatchProcessing().listFiles());

//		jTextForOpenCalaisToAnalyzeTextPane.setText(strbif.toString());
		strbif = null;

	}// GEN-LAST:event_jButton2ActionPerformed
	private void buildListOfFilesAndDirectoriesRecurivlyForStringBuilder(File[] sourfilestuff) {
		for (File perfile : sourfilestuff) {
			if (perfile.isDirectory()) {
				strbif = strbif.append(perfile.getAbsolutePath());
				strbif = strbif.append("\n");
				buildListOfFilesAndDirectoriesRecurivlyForStringBuilder(perfile.listFiles());
			} else {
				strbif = strbif.append("-----");
				strbif = strbif.append(perfile.getAbsolutePath());
				strbif = strbif.append("\n");
			}
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JButton jExtractTextToTextFieldButton;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jResultsPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jSelectFileToReadTextTextField;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JButton jStartSelectTextFileDialogForTextButton;
	private javax.swing.JTextPane jTextPane1;
	private JButton button;
}
